apiVersion: v1
kind: Pod
metadata:
  name: Node-selector-demo
  labels:
    env: test
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: Always
  nodeSelector:
    disktype: ssd