apiVersion: v1
kind: Pod
metadata:
  name: node-selector-demo
  labels:
    env: test
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: Always
  nodeSelector:
    disktype: ssd

##kubectl label nodes ip-192-168-32-167.ec2.internal disktype=ssd
##Here we are labeling the node based on disk type and setting the image pull poliicy as always...