apiVersion: v1
kind: Pod
metadata:
  name: node-selector-demo-1
  labels:
    env: test
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: Always
  nodeSelector:
    disktype: ssd
  tolerations:
  - key: "key1"
    operator: "Equal"
    value: "value1"
    effect: "NoExecute"
  - key: "key1"
    operator: "Equal"
    value: "value1"
    effect: "NoSchedule"

##kubectl taint nodes ip-192-168-32-167.ec2.internal key1=value1:NoSchedule
##kubectl taint nodes ip-192-168-32-167.ec2.internal key1=value1:NoExecute
##Here we are tainting the node on NoSchedule and NoExecute values
##So we are tolerating the pod to run node based on two values...
##And also we using Node Selector also for better results..